#include "port.h"
require 'port'
require 'error'
require 'object'


    rb_eIOError = rb_define_class("IOError", rb_eStandardError);
    rb_eEOFError = rb_define_class("EOFError", rb_eIOError);
    rb_define_global_function("syscall", rb_f_syscall, -1);
    rb_define_global_function("open", rb_f_open, -1);
    rb_define_global_function("printf", rb_f_printf, -1);
    rb_define_global_function("print", rb_f_print, -1);
    rb_define_global_function("putc", rb_f_putc, 1);
    rb_define_global_function("puts", rb_f_puts, -1);
    rb_define_global_function("gets", rb_f_gets, -1);
    rb_define_global_function("readline", rb_f_readline, -1);
    rb_define_global_function("getc", rb_f_getc, 0);
    rb_define_global_function("select", rb_f_select, -1);
    rb_define_global_function("readlines", rb_f_readlines, -1);
    rb_define_global_function("`", rb_f_backquote, 1);
    rb_define_global_function("p", rb_f_p, -1);
    rb_define_method(rb_mKernel, "display", rb_obj_display, -1);
    rb_cIO = rb_define_class("IO", rb_cObject);
    rb_define_singleton_method(rb_cIO, "new", rb_io_s_new, -1);
    rb_define_method(rb_cIO, "initialize", rb_io_initialize, -1);
    rb_define_singleton_method(rb_cIO, "popen", rb_io_s_popen, -1);
    rb_define_singleton_method(rb_cIO, "foreach", rb_io_s_foreach, -1);
    rb_define_singleton_method(rb_cIO, "readlines", rb_io_s_readlines, -1);
    rb_define_singleton_method(rb_cIO, "select", rb_f_select, -1);
    rb_define_singleton_method(rb_cIO, "pipe", rb_io_s_pipe, 0);
    rb_define_hooked_variable("$,", &rb_output_fs, 0, rb_str_setter);
    rb_define_hooked_variable("$/", &rb_rs, 0, rb_str_setter);
    rb_define_hooked_variable("$-0", &rb_rs, 0, rb_str_setter);
    rb_define_hooked_variable("$\\", &rb_output_rs, 0, rb_str_setter);
    rb_define_hooked_variable("$.", &lineno, 0, lineno_setter);
    rb_define_virtual_variable("$_", rb_lastline_get, rb_lastline_set);
    rb_define_method(rb_cIO, "clone", rb_io_clone, 0);
    rb_define_method(rb_cIO, "reopen", rb_io_reopen, -1);
    rb_define_method(rb_cIO, "print", rb_io_print, -1);
    rb_define_method(rb_cIO, "putc", rb_io_putc, 1);
    rb_define_method(rb_cIO, "puts", rb_io_puts, -1);
    rb_define_method(rb_cIO, "printf", rb_io_printf, -1);
    rb_define_method(rb_cIO, "each",  rb_io_each_line, -1);
    rb_define_method(rb_cIO, "each_line",  rb_io_each_line, -1);
    rb_define_method(rb_cIO, "each_byte",  rb_io_each_byte, 0);
    rb_define_method(rb_cIO, "syswrite", rb_io_syswrite, 1);
    rb_define_method(rb_cIO, "sysread",  rb_io_sysread, 1);
    rb_define_method(rb_cIO, "fileno", rb_io_fileno, 0);
    rb_define_alias(rb_cIO, "to_i", "fileno");
    rb_define_method(rb_cIO, "to_io", rb_io_to_io, 0);
    rb_define_method(rb_cIO, "sync",   rb_io_sync, 0);
    rb_define_method(rb_cIO, "sync=",  rb_io_set_sync, 1);
    rb_define_method(rb_cIO, "lineno",   rb_io_lineno, 0);
    rb_define_method(rb_cIO, "lineno=",  rb_io_set_lineno, 1);
    rb_define_method(rb_cIO, "readlines",  rb_io_readlines, -1);
    rb_define_method(rb_cIO, "read",  io_read, -1);
    rb_define_method(rb_cIO, "write", io_write, 1);
    rb_define_method(rb_cIO, "gets",  rb_io_gets_m, -1);
    rb_define_method(rb_cIO, "readline",  rb_io_readline, -1);
    rb_define_method(rb_cIO, "getc",  rb_io_getc, 0);
    rb_define_method(rb_cIO, "readchar",  rb_io_readchar, 0);
    rb_define_method(rb_cIO, "ungetc", rb_io_ungetc, 1);
    rb_define_method(rb_cIO, "<<",    rb_io_addstr, 1);
    rb_define_method(rb_cIO, "flush", rb_io_flush, 0);
    rb_define_method(rb_cIO, "tell", rb_io_tell, 0);
    rb_define_method(rb_cIO, "seek", rb_io_seek, -1);
rb_define_const(rb_cIO, "SEEK_SET", IO::SEEK_SET);
rb_define_const(rb_cIO, "SEEK_CUR", IO::SEEK_CUR);
rb_define_const(rb_cIO, "SEEK_END", IO::SEEK_END);
    rb_define_method(rb_cIO, "rewind", rb_io_rewind, 0);
    rb_define_method(rb_cIO, "pos", rb_io_tell, 0);
    rb_define_method(rb_cIO, "pos=", rb_io_set_pos, 1);
    rb_define_method(rb_cIO, "eof", rb_io_eof, 0);
    rb_define_method(rb_cIO, "eof?", rb_io_eof, 0);
    rb_define_method(rb_cIO, "close", rb_io_close_m, 0);
    rb_define_method(rb_cIO, "closed?", rb_io_closed, 0);
    rb_define_method(rb_cIO, "close_read", rb_io_close_read, 0);
    rb_define_method(rb_cIO, "close_write", rb_io_close_write, 0);
    rb_define_method(rb_cIO, "isatty", rb_io_isatty, 0);
    rb_define_method(rb_cIO, "tty?", rb_io_isatty, 0);
    rb_define_method(rb_cIO, "binmode",  rb_io_binmode, 0);
    rb_define_method(rb_cIO, "ioctl", rb_io_ioctl, -1);
    rb_define_method(rb_cIO, "fcntl", rb_io_fcntl, -1);
    rb_define_method(rb_cIO, "pid", rb_io_pid, 0);
    rb_define_hooked_variable("$stdin", &rb_stdin, 0, set_stdin);
    rb_define_hooked_variable("$stdout", &rb_stdout, 0, set_stdout);
    rb_define_hooked_variable("$stderr", &rb_stderr, 0, set_stderr);
    rb_define_hooked_variable("$>", &rb_defout, 0, rb_io_defset);
    rb_define_hooked_variable("$defout", &rb_defout, 0, rb_io_defset);
rb_define_global_const("STDIN", :STDIN);
rb_define_global_const("STDOUT", :STDOUT);
rb_define_global_const("STDERR", :STDERR);
    rb_define_readonly_variable("$<", $<);
rb_define_global_const("ARGF", :ARGF);

# TODO: just make ARGF an actual array... these hacks are dumb.
# IGNORE    rb_define_singleton_method(argf, "fileno", argf_fileno, 0);
# IGNORE    rb_define_singleton_method(argf, "to_i", argf_fileno, 0);
# IGNORE    rb_define_singleton_method(argf, "to_io", argf_to_io, 0);
# IGNORE    rb_define_singleton_method(argf, "each",  argf_each_line, -1);
# IGNORE    rb_define_singleton_method(argf, "each_line",  argf_each_line, -1);
# IGNORE    rb_define_singleton_method(argf, "each_byte",  argf_each_byte, 0);
# IGNORE    rb_define_singleton_method(argf, "read",  argf_read, -1);
# IGNORE    rb_define_singleton_method(argf, "readlines", rb_f_readlines, -1);
# IGNORE    rb_define_singleton_method(argf, "to_a", rb_f_readlines, -1);
# IGNORE    rb_define_singleton_method(argf, "gets", rb_f_gets, -1);
# IGNORE    rb_define_singleton_method(argf, "readline", rb_f_readline, -1);
# IGNORE    rb_define_singleton_method(argf, "getc", argf_getc, 0);
# IGNORE    rb_define_singleton_method(argf, "readchar", argf_readchar, 0);
# IGNORE    rb_define_singleton_method(argf, "tell", argf_tell, 0);
# IGNORE    rb_define_singleton_method(argf, "seek", argf_seek, -1);
# IGNORE    rb_define_singleton_method(argf, "rewind", argf_rewind, 0);
# IGNORE    rb_define_singleton_method(argf, "pos", argf_tell, 0);
# IGNORE    rb_define_singleton_method(argf, "pos=", argf_set_pos, 1);
# IGNORE    rb_define_singleton_method(argf, "eof", argf_eof, 0);
# IGNORE    rb_define_singleton_method(argf, "eof?", argf_eof, 0);
# IGNORE    rb_define_singleton_method(argf, "binmode", argf_binmode, 0);
# IGNORE    rb_define_singleton_method(argf, "to_s", argf_filename, 0);
# IGNORE    rb_define_singleton_method(argf, "filename", argf_filename, 0);
# IGNORE    rb_define_singleton_method(argf, "file", argf_file, 0);
# IGNORE    rb_define_singleton_method(argf, "skip", argf_skip, 0);
# IGNORE    rb_define_singleton_method(argf, "close", argf_close, 0);
# IGNORE    rb_define_singleton_method(argf, "closed?", argf_closed, 0);
# IGNORE    rb_define_singleton_method(argf, "lineno",   argf_lineno, 0);
# IGNORE    rb_define_singleton_method(argf, "lineno=",  argf_set_lineno, 1);
    rb_define_readonly_variable("$FILENAME", &filename);
    rb_define_virtual_variable("$-i", opt_i_get, opt_i_set);

